### ISSUE TITLE
example of angsd --> ngsF ?

### ISSUE THREAD

**Issue by z0on** [fgvieira/ngsF#12]
Dear Felipe - does ngsF take the same input GLF file as ngsLD?
For some reason I cannot seem to find the right combination of ANGSD's -doGeno and/or -doGlf to produce a file that ngsF would accept...
many thanks in advance
Misha

**Comment by fgvieira** [comment]
Hi Misha,

`ngsF` accepts `ANGSD` outpu file from `-doGlf 3`; you can find some example [here](https://github.com/fgvieira/ngsF/blob/master/examples/test.sh).
