### ISSUE TITLE
cannot read glf

### ISSUE THREAD

**Issue by z0on** [fgvieira/ngsF#13]
Hi Felipe - I am sure it is something silly, but I am out of ideas... For some reason I cannot get this to work:

NIND=`cat bams.nr | wc -l`
NS=`zcat g3.mafs.gz | wc -l`
zcat g3.glf.gz | ngsF --glf - --n_ind $NIND --n_sites $NS --out inbr

I'm getting "ERROR: cannot read GLF file!"

I made sure to make g3.glf.gz with -doGlf 3. What am I doing wrong?
I have the most recent angsd, version 0.933-25-g5955d69 (htslib: 1.9-44-g80f3557)

cheers
Misha

**Comment by fgvieira** [comment]
I don't think the error is because of this, but it is worth a try.
I think the `NS` should be:
```
NS=$((`zcat g3.mafs.gz | wc -l`-1))
```
since the MAFs file has a header.

**Comment by z0on** [comment]
Damn, you are right! problem solved, thanks!
Misha
