### ISSUE TITLE
Supplementary figures 7, 8 and 9

### ISSUE THREAD

**Issue by mpalmada** [fgvieira/ngsF#20]
Dear @fgvieira,

I have run ngsF and got as output a text file with per individual inbreeding values and a .pars binary file. I would like to know how did you manage with those files to obtain a figure similar to the supplementary figures 7, 8 and 9 of the paper (https://academic.oup.com/bioinformatics/article/32/14/2096/1743296). I have read that you only used ggplot2 but I am not sure how to process the binary file to get a table with the values and so on.

Thanks a lot,

Sincerely,

Marc

**Comment by fgvieira** [comment]
Figures show how inbreeding can influence calling genotypes and SFS estimation.
For that, you need to call genotypes (or estimate SFS) with the inferred inbreeding coefficients (I used ANGSD) and compare the results with the truth.
