### ISSUE TITLE
Merge glf.gz from different chromosome

### ISSUE THREAD

**Issue by biozzq** [fgvieira/ngsF#8]
Hi @fgvieira 

I have run `doGlf 3` for each chromosome using angsd. In order to estimate inbreeding coefficient, I think I should merge the binary glf.gz together from each chromosome, but I do not know which software can do this.

Best
Zhuqing

**Comment by fgvieira** [comment]
Dear Zhuqing,

if you have GLF files from ANGSD `-doGlf 3`, you can merge them by simply `zcat` and gzip them:

`zcat 1.glf.gz 2.glf.gz .... | gzip - >merge.glf.gz`

Best,
